name: Continuous Delivery
on:
  push:
    branches:
      - master
env:
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
jobs: 
  upload-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build